steps:
- id: 'Unit Tests'
  name: 'golang:1.21-alpine'
  script: |
    apk add build-base
    go mod download
    go build -o /sdx-image
    go test ./...
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
